import { Barlow } from 'next/font/google'
import Navbar from '@/components/Navbar'
import './globals.css'

const barlow = Barlow({ subsets: ['latin'], weight: ['600', '800'] })

export const metadata = {
  title: 'Review App',
  description: 'Generated by Dardo Altobelli'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body className={barlow.className + ' bg-slate-900 text-white max-w-screen-md mx-auto'}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
